[package]
name = "seme"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
colored = "2.1.0"
confy = "0.6.1"
dirs = "5.0.1"
isahc = "1.7.2"
linku-sona = "0.1"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
